In [ ]:
import pandas as pd 

df = pd.read_csv('../../data/raw/raw_imf_trade.csv')

In [3]:
df.head()

,COUNTRY,INDICATOR,COUNTERPART_COUNTRY,FREQUENCY,TIME_PERIOD,OBS_VALUE,SCALE
0,Bermuda,"Imports of goods, Free on board (FOB), US dollar",Burkina Faso,Annual,1996.0,0.000072,Millions
1,Bermuda,"Imports of goods, Free on board (FOB), US dollar",Burkina Faso,Annual,2009.0,0.001812,Millions
2,Bermuda,"Imports of goods, Free on board (FOB), US dollar",Burkina Faso,Annual,2011.0,0.044988,Millions
3,Bermuda,"Imports of goods, Free on board (FOB), US dollar",Burkina Faso,Annual,2018.0,0.000178,Millions
4,Bermuda,"Imports of goods, Free on board (FOB), US dollar",Burkina Faso,Annual,2024.0,0.000459,Millions

In [13]:
print(df.shape)
print(df.columns)
print(df.isna().sum().to_string())

(114301, 7)
Index(['COUNTRY', 'INDICATOR', 'COUNTERPART_COUNTRY', 'FREQUENCY',
       'TIME_PERIOD', 'OBS_VALUE', 'SCALE'],
      dtype='object')
COUNTRY                 0
INDICATOR               0
COUNTERPART_COUNTRY     0
FREQUENCY               0
TIME_PERIOD            50
OBS_VALUE              50
SCALE                  49

In [16]:
cdf = df.copy()

cdf = cdf.drop(columns=['FREQUENCY', 'SCALE'])

cdf.rename(columns={
    'COUNTRY': 'country_a',
    'INDICATOR': 'import_export',
    'COUNTERPART_COUNTRY': 'country_b',
    'TIME_PERIOD': 'year',
    'OBS_VALUE': 'value_mill_dollar'
}, inplace=True)

cdf.head()

,country_a,import_export,country_b,year,value_mill_dollar
0,Bermuda,"Imports of goods, Free on board (FOB), US dollar",Burkina Faso,1996.0,0.000072
1,Bermuda,"Imports of goods, Free on board (FOB), US dollar",Burkina Faso,2009.0,0.001812
2,Bermuda,"Imports of goods, Free on board (FOB), US dollar",Burkina Faso,2011.0,0.044988
3,Bermuda,"Imports of goods, Free on board (FOB), US dollar",Burkina Faso,2018.0,0.000178
4,Bermuda,"Imports of goods, Free on board (FOB), US dollar",Burkina Faso,2024.0,0.000459

In [34]:

cdf['import_export'] = cdf['import_export'].replace('Imports of goods, Free on board (FOB), US dollar', 'import')
cdf['import_export'] = cdf['import_export'].replace('Exports of goods, Free on board (FOB), US dollar', 'export')

print("Import count:", sum(cdf['import_export'] == 'import'))
print("Export count:", sum(cdf['import_export'] == 'export'))

Import count: 55886
Export count: 58415

In [35]:
unique = cdf['year'].unique()
print(unique)

[1996. 2009. 2011. 2018. 2024. 2023. 1992. 1994. 1995. 1997. 1998. 1999.
 2000. 2001. 2003. 2004. 2006. 2007. 2008. 2010. 2012. 2013. 2014. 2015.
 2016. 2017. 2019. 2020. 2021. 2022. 1990. 1993. 2002. 2005. 1991.   nan]

In [38]:
# Remove the last character from all values in a column
cdf['year'] = cdf['year'].astype(str).str[:-1]

unique = cdf['year'].unique()
print(unique)

['1996' '2009' '2011' '2018' '2024' '2023' '1992' '1994' '1995' '1997'
 '1998' '1999' '2000' '2001' '2003' '2004' '2006' '2007' '2008' '2010'
 '2012' '2013' '2014' '2015' '2016' '2017' '2019' '2020' '2021' '2022'
 '1990' '1993' '2002' '2005' '1991' 'n']

In [44]:
# Select rows where COUNTRY is 'USA'
nan_rows = cdf[cdf['year'] == 'n']
print(nan_rows)

Empty DataFrame
Columns: [country_a, import_export, country_b, year, value_mill_dollar]
Index: []

In [ ]:
cdf = cdf.dropna(subset=['value_mill_dollar'])
print(nan_rows)

Empty DataFrame
Columns: [country_a, import_export, country_b, year, value_mill_dollar]
Index: []

In [48]:
cdf.head(40)

,country_a,import_export,country_b,year,value_mill_dollar
0,Bermuda,import,Burkina Faso,1996,0.000072
1,Bermuda,import,Burkina Faso,2009,0.001812
2,Bermuda,import,Burkina Faso,2011,0.044988
3,Bermuda,import,Burkina Faso,2018,0.000178
4,Bermuda,import,Burkina Faso,2024,0.000459
5,Solomon Islands,import,"Uzbekistan, Republic of",2023,0.008973
6,Brazil,import,"Azerbaijan, Republic of",1992,0.701000
7,Brazil,import,"Azerbaijan, Republic of",1994,3.222000
8,Brazil,import,"Azerbaijan, Republic of",1995,5.252000
9,Brazil,import,"Azerbaijan, Republic of",1996,6.660487
10,Brazil,import,"Azerbaijan, Republic of",1997,3.357000
11,Brazil,import,"Azerbaijan, Republic of",1998,0.575000
12,Brazil,import,"Azerbaijan, Republic of",1999,0.375000
13,Brazil,import,"Azerbaijan, Republic of",2000,1.110390
14,Brazil,import,"Azerbaijan, Republic of",2001,0.684899
15,Brazil,import,"Azerbaijan, Republic of",2003,0.101449
16,Brazil,import,"Azerbaijan, Republic of",2004,0.004323
17,Brazil,import,"Azerbaijan, Republic of",2006,77.627951
18,Brazil,import,"Azerbaijan, Republic of",2007,643.235664
19,Brazil,import,"Azerbaijan, Republic of",2008,0.193952
20,Brazil,import,"Azerbaijan, Republic of",2009,0.150171
21,Brazil,import,"Azerbaijan, Republic of",2010,0.193980
22,Brazil,import,"Azerbaijan, Republic of",2011,0.043431
23,Brazil,import,"Azerbaijan, Republic of",2012,0.179932
24,Brazil,import,"Azerbaijan, Republic of",2013,0.291068
25,Brazil,import,"Azerbaijan, Republic of",2014,0.231199
26,Brazil,import,"Azerbaijan, Republic of",2015,0.212286
27,Brazil,import,"Azerbaijan, Republic of",2016,0.144071
28,Brazil,import,"Azerbaijan, Republic of",2017,0.183431
29,Brazil,import,"Azerbaijan, Republic of",2018,0.587611
30,Brazil,import,"Azerbaijan, Republic of",2019,0.390168
31,Brazil,import,"Azerbaijan, Republic of",2020,0.672401
32,Brazil,import,"Azerbaijan, Republic of",2021,48.517317
33,Brazil,import,"Azerbaijan, Republic of",2022,3.829966
34,Brazil,import,"Azerbaijan, Republic of",2023,0.364808
35,Brazil,import,"Azerbaijan, Republic of",2024,23.127866
36,Brazil,import,Grenada,1990,0.034000
37,Brazil,import,Grenada,1993,0.011000
38,Brazil,import,Grenada,1994,0.085000
39,Brazil,import,Grenada,1995,0.211000

In [49]:
cdf.to_csv('../../data/raw/imf_trade.csv', index=False)